[package]
name = "pavetta"
version = "0.1.0"
authors = ["Mikhail Pankov <mikhail.pankov@kaspersky.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hlua = "0.4.1"
